version: '3.8'

services:
  backend:
    build: .
    command: python core/test.py
    container_name: backend
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    env_file:
      - dev.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
  postgres_data:
  static_volume:
  media_volume:
