# version: '3.8'

services:
  backend:
    build: .
    command: ping 127.0.0.1
    container_name: collage-backend
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: collage-postgres
    env_file:
      - dev.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zq(4lse44e)y3112*6!
      POSTGRES_DB: collage_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume:
